//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Services.EAChatService.Contract.Request
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/EA.Services.EAChatService.Contract.Reques" +
        "t")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EA.Services.EAChatService.Contract.Request.Message))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/EA.Services.EAChatService.Contract.Reques" +
        "t")]
    public partial class Message : EA.Services.EAChatService.Contract.Request.RequestBase
    {
        
        private string SimpleMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SimpleMessage
        {
            get
            {
                return this.SimpleMessageField;
            }
            set
            {
                this.SimpleMessageField = value;
            }
        }
    }
}
namespace EA.Services.EAChatService.Contract.Response
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponsePacket", Namespace="http://schemas.datacontract.org/2004/07/EA.Services.EAChatService.Contract.Respon" +
        "se")]
    public partial class ResponsePacket : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ResponseMessageField;
        
        private System.DateTime TimeStampField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage
        {
            get
            {
                return this.ResponseMessageField;
            }
            set
            {
                this.ResponseMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp
        {
            get
            {
                return this.TimeStampField;
            }
            set
            {
                this.TimeStampField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEAChatService", CallbackContract=typeof(IEAChatServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IEAChatService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAChatService/Send", ReplyAction="http://tempuri.org/IEAChatService/SendResponse")]
    void Send(EA.Services.EAChatService.Contract.Request.Message message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAChatService/Send", ReplyAction="http://tempuri.org/IEAChatService/SendResponse")]
    System.Threading.Tasks.Task SendAsync(EA.Services.EAChatService.Contract.Request.Message message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEAChatServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAChatService/ResponseMessage", ReplyAction="http://tempuri.org/IEAChatService/ResponseMessageResponse")]
    void ResponseMessage(EA.Services.EAChatService.Contract.Response.ResponsePacket response);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEAChatServiceChannel : IEAChatService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EAChatServiceClient : System.ServiceModel.DuplexClientBase<IEAChatService>, IEAChatService
{
    
    public EAChatServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public EAChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public EAChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public EAChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public EAChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void Send(EA.Services.EAChatService.Contract.Request.Message message)
    {
        base.Channel.Send(message);
    }
    
    public System.Threading.Tasks.Task SendAsync(EA.Services.EAChatService.Contract.Request.Message message)
    {
        return base.Channel.SendAsync(message);
    }
}
